### ISSUE TITLE
why 3d texture create with layer not depth?

### ISSUE THREAD

**Issue by yangfengzzz** [donmccurdy/KTX2-Samples#1]
the 3d textures are generated by using --layers, which will be texture2d array in my code. why not use --depth?

**Comment by donmccurdy** [comment]
I think this was probably an oversight on my part. three.js does not support 3D textures in compressed formats yet, so I have limited ability to test in this area, but I'll fix the `encode.sh` script in any case. Thanks!

Note to self — as Mark mentions in https://github.com/KhronosGroup/KTX-Software/issues/826#issuecomment-1870219801, KTX Software cannot yet generate mipmaps for 3D textures, so I'll want to omit that flag from the script as well.

**Comment by donmccurdy** [comment]
Fixed in 2bce246e3db5dd83e3b051b7124de620da5da464, thanks!
